language: node_js
services: docker
node_js: 6.10

env:
  global:

    - AWS_ACCESS_KEY_ID=AKIAIZYDGQ7PKG27OFJQ
    - AWS_DEFAULT_REGION=ap-southeast-2

    # SLACK_HOOK_DEV
    - secure: fFs+/eD3LREWOpL/ItKheCN2OS51drZXk0txCCpS3k18okGm3X4Mz5MD7FxTRS6+VyN1h7wzXaBBCWHozcJwTqIFGEEagXjNRjoDaZFQLxY1wf+uZ1bV1zN5XtSFrFCXXWL6BhihsYp3B2j6z2HUfIUMG88Jj7dVBG8dWuVAEUHBLhU7wf3R5Q8QIhvRsyCS0HVYNBkpb1nt8FZtGpoaRalx+sYoeVR731pZa5N19GdCfnqtn0Pp/oAXsFuL60WOA6/iMU3vzh/Uj1phBTGHL7YtBr+HXziwCf0iLdxorA3A4twZQZHLWUYMHySB2G0+FaX5dSAy6Qn1luQTYADVW5iskccTTvKEOu4uXfUMFj3SDOibCrWKlIZtl+oWDsM6583EmmVB4oBGE8lQv9YRTWF8R6M/7GKJcuY6SO1eVWcUpg82gg0iShiOdOrXpSItCTpq4q2jqOfWWF+xKJARG+1Q7viNeQvkz4JVDrNx9SGJe8E01IA+pBvUU0z7lvL9cTy2obmVd0UkIFmMYvfl2TVlPNVCOR1BV56YYP4YQ64jIGvtIVE9H1oT3jrTHJmpm/ozxzBeteBU2jJomz0LnN/IT3mneRfzNlx+LpDBhdAoaidjh1aywpLMw7EhtAgAQb/gdC1Cr3EORoaky5HEagYWRWEz8/mdYbY/3qwrBWU=

    # SLACK_HOOK_PROD
    - secure: ewvN1Q96mZt/iR+jnTkZCyxWIMPWhzgQvCNwlvQZhfw1MrPN8tyKy4w60injpU4yktZs+QxSZaCEYgEWoZipsUx2+BJ8QknRI2lFLo9ZjCqfkSS8ZpgLxw4rVjVXadJFsv4DZ704M5wGIWakLz/sFW8sciuooF1QTl9DC5COO2FCELjsTLn5flEDuMN+a7M13ArSi0mN8WQaavzrCZCMzrHR0Ch6DD1XcIxNG7l31jgfYIl7a1nGJg0hoqw0GQBFeBzOiC0+cykEUeErWcq4XGCuP3jhEVixhrFvKdUld5NsFEzEgHhCQDVeGh3+XpqXiBajduNBAJGiTuR2HOclhx4oox7RKMNqoN8fSIcAeq2kEMSIN5X/1W1tIxKz3oVuQ2eRYENaC8yzCaglXwYDkwb/uNo5oe8jYHv6douvZwafwocR03Wu8Ty0T5yHw2/9qNqZl+Qy/xhl9jbNFo7OvG7RnWTgZYAgJN5jN8kjc+B/gKtWk/QPetKurVf1fdJtTNdzUM3SAmFajYiDzHJh+Q4g801EhznJA1l4M93FHrMa0lFu4wYQgo0TVgMEPEuAhmhVtprFP40SD9ZYcH8Mlijrc36crbebCATqndpj+U4mS0eCQSvsSRVcmZYN6hicqRm0zGmHcO+7hHSoHOvfoQ9ISTN2AkcEuPACQIxSGGg=

    # AWS_SECRET_ACCESS_KEY
    - secure: fTbRlIS4++/NN1NYUsAEf8mz/Bg8dOUEk/1h/X95QUcZYs+0wOWSQ8E+T1bcgMekIOtR31kzgQkgI1vK4tDTY/p8w1lNPyAwSsXYJlYNI7plUs+wOf544iwoKj9rFykF9bSTgwrVu6w+W4cztdIdh5lVi8G7fHQgOQtgo7OFIwhnRuFZ8Yqc0JCXax8aDXHWTMrKqfpzdtgN6ID+xpUCPJeMHyRTV5/jxreH92TbWB6yX/zfeQeJ6BgPM/cAzwv8GH1s9wjbYl0fyOUloAYAYb6KtBehYk7xlrV2GKLXnpxYRDBr6wlsEq1lKyYywvHEEx/OuEyNV7VeSbbQbqIBg0vcEsE3YIu/v38nWhwEQ3Cje3jqvOPpn7NSXl1wX4bUvbed0KjDkG70C3qVJK4qBUK4HsPz5tX98quQuoDtIf6YOa0QhOexjJGrDU6VJ966Em6rwdEJH6c1VRxTArxIMSyRCjBT8F3e69GAKRFg80q7UcuoqCVd4qy6Es1TjWlWRZI24qE9LfExMlee3U15qKkOwsFMC1l3clVwna7UUsNEHzpPPgbhbNf9cEMVFKP9oti0OTILgiK2JRoOhwShGWS30yV7DrkK2iBZR9xKzZtelLjdbtdHBAKSZEeK3NAaIlLPHImHH7GmAETcexF9KVmoCundIsLIisLzQxomrfI=

cache:
  yarn: true
  directories:
    - node_modules

# Skip builds on version tags, as they'll occur on the branch anyway.
branches:
  except:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

install:

  # Install dependencies.
  - yarn

  # Install Terraform for checking infrastructure configuration.
  - curl --location https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip > terraform.zip
  - unzip terraform.zip
  - terraform() { "${TRAVIS_BUILD_DIR}/terraform" "$@"; }

script:

  # Check that Terraform config files are formatted correctly and that they validate.
  - export TF_VAR_slack_hook_dev="${SLACK_HOOK_DEV}"
  - export TF_VAR_slack_hook_prod="${SLACK_HOOK_PROD}"
  - terraform fmt -check infrastructure/
  - ( cd infrastructure && terraform init -input=false -lock=false )
  - ( cd infrastructure && terraform validate )

  # As state is stored remotely, we can also check that the state is up-to-date - i.e. that no
  # changes have been pushed without being applied. We only care about the exit code here, and don't
  # want to expose any potentially sensitive data, so we also redirect the output.
  - ( cd infrastructure && terraform plan -detailed-exitcode -lock=false > /dev/null )

  # Get key info for deployment from Terraform variables.
  - export LAMBDA_NAME="$( cd infrastructure && terraform output function_name )"
  - export LAMBDA_DESCRIPTION="$( cd infrastructure && terraform output function_description )"
  - export LAMBDA_TIMEOUT="$( cd infrastructure && terraform output function_timeout )"
  - export LAMBDA_MODULE="$( cd infrastructure && terraform output function_module )"
  - export LAMBDA_HANDLER="$( cd infrastructure && terraform output function_handler )"
  - export LAMBDA_ROLE="$( cd infrastructure && terraform output function_role )"
  - export LAMBDA_ALIAS="$( cd infrastructure && terraform output function_alias )"
  - export LAMBDA_RUNTIME="$( cd infrastructure && terraform output function_runtime )"
  - export SNS_TOPIC_DEV="$( cd infrastructure && terraform output sns_topic_dev )"

  # Linting and testing.
  - yarn lint
  - yarn test

before_deploy:

  # Clean up dependencies + unneeded files, and reinstall production dependencies only.
  - rm -rf coverage infrastructure node_modules tests .*rc.js
  - yarn --prod

deploy:

  # Deploy to $LATEST on dev branch. (i.e. don't publish a new version).

  - on:
      branch: dev
    publish: false

    provider: lambda
    function_name: $LAMBDA_NAME
    region: $AWS_DEFAULT_REGION
    role: $LAMBDA_ROLE
    description: $LAMBDA_DESCRIPTION
    runtime: $LAMBDA_RUNTIME
    timeout: $LAMBDA_TIMEOUT
    module_name: $LAMBDA_MODULE
    handler_name: $LAMBDA_HANDLER
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true

  # Deploy and publish a new version on master branch.

  - on:
      branch: master
    publish: true

    provider: lambda
    function_name: $LAMBDA_NAME
    region: $AWS_DEFAULT_REGION
    role: $LAMBDA_ROLE
    description: $LAMBDA_DESCRIPTION
    runtime: $LAMBDA_RUNTIME
    timeout: $LAMBDA_TIMEOUT
    module_name: $LAMBDA_MODULE
    handler_name: $LAMBDA_HANDLER
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY

after_deploy:

  # Set a Lambda alias to the most recently deployed version.
  - if [ "master" = "${TRAVIS_BRANCH}" ]; then
      pip install awscli --upgrade --user;
      export MOST_RECENT=$(aws lambda list-versions-by-function --function "${LAMBDA_NAME}" --max-items 10000 | node -e "let stdin=''; process.stdin.on('data',(chunk)=>{stdin+=chunk}).on('end',()=>{console.log(JSON.parse(stdin).Versions.pop().Version)})");
      aws lambda update-alias --function-name "${LAMBDA_NAME}" --name "${LAMBDA_ALIAS}" --function-version "${MOST_RECENT}";
    fi;

notifications:
  email: false
  webhooks:
    urls: https://api.tm.id.au/dev/travis/jobStatus
  slack:
    on_start: always
    rooms:
      - secure: NIJMe7vHNS3JwNYW6YS/St5VgMWtaebI2AacQIuNCZFPVrs/mThhwwQe0hj31xC3BYq0LCAQLxnofO0HJKE9/p5f7uYBOWsFoMhhaw6B932dvFh2oKidDGTqirRaVp1XpbVGgC3/C+MkufcRAOwhqthu23H0JZkf42cqDw7ari8g9VPIKlWFtvOrNuGziNbDy2R9y0bNOmcvUJ0DVOqQMf72hT6VFQns8x4Bz9LYgAB+NZVVy/NOK+Ehr2RArPBbqhaVIDswi1IeCK94SFjur+OeVoxvsQYOAlM5CIC6ZF04FDaO+t9p30GtIccufjU6zSNRc618ozv/2NHE8XdoiAqAdE2IcLhdTwAGnbiFcCM/3V7UnasLAH+vsjwxQf+kSv1QgqunaGUq69vcK3fUZhgER08tZrDT/wsLNZ+0819+ujv3dwBM7pVzYioYPwHM/RyCHnrLLmie6zrSuwVCitmkAFC+dDK3Lz5Qg0iKRNIfpSBywjH3jOhhvOREVcgFVeGY2XeGU1ApB0Ug0A878Y/CdVE9fbgFVLCEKZGgOE1rMM2TFQBpF7r2vwY1HNEE2SC4PInSAKN592qhkygbrJVaDLPPoXph8DSAYBNPoddWnsMi8Nx+KgaPQeIiDsBVSbPFNWYfWuEY293KisNS6fHA6hI718dPaRoJeVwxwec=
